/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import funkcje.OperacjeNaPlikach;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JRadioButton;
import mail.Kontakt;
import mail.listaKontaktow;
import view.Kontakty;

/**
 *
 * @author 
 */
public class DodajKontakt extends javax.swing.JFrame {

    /**
     * Creates new form DodajKontakt
     */
    
    
    public DodajKontakt(JList lista,JButton btnDodaj, listaKontaktow listaK) {
        initComponents();
        
        //kontakty2 = kontakty;
        
        lista2 = lista;
        
        btnDodaj2 = btnDodaj;
        
        listaK2 = listaK;
        
        //kontakty2.btnDodaj2.setEnabled(true);
        
        
        setLocationRelativeTo(null);
        //((JRadioButton) rbOsoba.getValueAt(0, 1)).setSelected(true);
        rbOsoba.setSelected(true);
        //setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        
        tfNazwa.setEnabled(false);
        lbNazwa.setEnabled(false);
        rbOsoba.setEnabled(false);
        lbError.setVisible(false);
        lbError2.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbImie = new javax.swing.JLabel();
        tfImie = new javax.swing.JTextField();
        lbNazwisko = new javax.swing.JLabel();
        tfNazwisko = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        rbOsoba = new javax.swing.JRadioButton();
        rbInstytucja = new javax.swing.JRadioButton();
        lbNazwa = new javax.swing.JLabel();
        tfNazwa = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taNotatki = new javax.swing.JTextArea();
        lbNotatki = new javax.swing.JLabel();
        btnDodaj = new javax.swing.JButton();
        btnWyczysc = new javax.swing.JButton();
        btnAnuluj = new javax.swing.JButton();
        lbError = new javax.swing.JLabel();
        lbError2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        lbImie.setText("Imię");

        lbNazwisko.setText("Nazwisko");

        lbEmail.setText("e-mail");

        rbOsoba.setText("Osoba");
        rbOsoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOsobaActionPerformed(evt);
            }
        });

        rbInstytucja.setText("Instytucja");
        rbInstytucja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbInstytucjaMouseClicked(evt);
            }
        });
        rbInstytucja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbInstytucjaActionPerformed(evt);
            }
        });

        lbNazwa.setText("Nazwa");

        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });

        taNotatki.setColumns(20);
        taNotatki.setRows(5);
        jScrollPane1.setViewportView(taNotatki);

        lbNotatki.setText("Notatki");

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnWyczysc.setText("Wyczyść");
        btnWyczysc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWyczyscActionPerformed(evt);
            }
        });

        btnAnuluj.setText("Anuluj");
        btnAnuluj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnulujActionPerformed(evt);
            }
        });

        lbError.setForeground(new java.awt.Color(255, 0, 0));
        lbError.setText("Niepoprawny email!");

        lbError2.setForeground(new java.awt.Color(255, 51, 51));
        lbError2.setText("Puste dane!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbOsoba)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbImie)
                            .addComponent(lbNazwisko))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfImie)
                                    .addComponent(tfNazwisko, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbInstytucja)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbNazwa)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfNazwa, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbError)
                                    .addComponent(lbError2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbEmail)
                                    .addComponent(lbNotatki))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnDodaj)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnWyczysc)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAnuluj))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tfEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)))))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbOsoba)
                            .addComponent(rbInstytucja))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbImie)
                                    .addComponent(tfImie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbError2))
                                .addGap(18, 18, 18)
                                .addComponent(lbNazwisko))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbNazwa)
                                    .addComponent(tfNazwa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(tfNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(lbError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmail))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNotatki))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAnuluj)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDodaj)
                        .addComponent(btnWyczysc)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        btnDodaj2.setEnabled(true);
    }//GEN-LAST:event_formWindowClosed

    private void btnAnulujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnulujActionPerformed
        // TODO add your handling code here:
        
        
        btnDodaj2.setEnabled(true);
        dispose();
    }//GEN-LAST:event_btnAnulujActionPerformed

    private void rbInstytucjaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbInstytucjaMouseClicked
        // TODO add your handling code here:
        
        
        rbOsoba.setSelected(false);
        lbNazwa.setEnabled(true);
        tfNazwa.setEnabled(true);
        lbImie.setEnabled(false);
        lbNazwisko.setEnabled(false);
        tfImie.setEditable(false);
        tfNazwisko.setEditable(false);
        rbInstytucja.setEnabled(false);
        rbOsoba.setEnabled(true);
        
        
    }//GEN-LAST:event_rbInstytucjaMouseClicked

    private void rbInstytucjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbInstytucjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbInstytucjaActionPerformed

    private void rbOsobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOsobaActionPerformed
        // TODO add your handling code here:
        rbInstytucja.setSelected(false);
        lbNazwa.setEnabled(false);
        tfNazwa.setEnabled(false);
        lbImie.setEnabled(true);
        lbNazwisko.setEnabled(true);
        tfImie.setEditable(true);
        tfNazwisko.setEditable(true);
        rbOsoba.setEnabled(false);
        rbInstytucja.setEnabled(true);
    }//GEN-LAST:event_rbOsobaActionPerformed

    private void btnWyczyscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWyczyscActionPerformed
        // TODO add your handling code here:
        tfImie.setText("");
        tfNazwisko.setText("");
        tfNazwa.setText("");
        tfEmail.setText("");
        taNotatki.setText("");
    }//GEN-LAST:event_btnWyczyscActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        // TODO add your handling code here:
        Kontakt nowyKontakt;
        if(rbOsoba.isSelected()){
        
            nowyKontakt = new Kontakt(tfImie.getText(), tfNazwisko.getText() 
                   ,tfEmail.getText()
                   ,taNotatki.getText());
                    
            
            
        }else
        {
            nowyKontakt =  new Kontakt(tfNazwa.getText(),
                    tfEmail.getText()
                    ,taNotatki.getText());
            
        }
        
        String Pusty = "";
        
        String EMAIL_PATTERN = 
        "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
        + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        
        Pattern pattern = Pattern.compile(EMAIL_PATTERN);
        Pattern pattern2 = Pattern.compile(Pusty);
        
        if((pattern2.matcher(tfImie.getText()).matches() != false) && 
                (pattern2.matcher(tfNazwisko.getText()).matches() != false) &&
                (rbOsoba.isSelected() == true))
        {
            lbError2.setVisible(true);
        }
        else if((pattern2.matcher(tfNazwa.getText()).matches() != false) &&
                (rbInstytucja.isSelected() == true))
        {    
            lbError.setVisible(true);
        }
                else if((pattern.matcher(tfEmail.getText()).matches() == false))
        {
            lbError.setVisible(true);
        }
        
        else
        {
            
          listaK2.dodajKontakt(nowyKontakt);  
            
        DefaultListModel model = new DefaultListModel();
    int i;
    for(i=0; i <= lista2.getLastVisibleIndex(); i++)
        model.addElement(lista2.getModel().getElementAt(i));
    
    model.add(i,nowyKontakt.getInfo());
    lista2.setModel(model);  
    //lista2.setForeground(Color.green);
            try {
                OperacjeNaPlikach onp = new OperacjeNaPlikach();
                onp.ZapisKontaktowDoPliku(listaK2);
            } catch (IOException ex) {
                Logger.getLogger(DodajKontakt.class.getName()).log(Level.SEVERE, null, ex);
            }
    
    dispose();
        }
    }//GEN-LAST:event_btnDodajActionPerformed

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DodajKontakt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DodajKontakt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DodajKontakt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DodajKontakt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new DodajKontakt().setVisible(true);
            }
        });
    }
    
   // private Kontakty kontakty2;
    private JButton btnDodaj2;
    private JList lista2;
    private listaKontaktow listaK2;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnuluj;
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnWyczysc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbError;
    private javax.swing.JLabel lbError2;
    private javax.swing.JLabel lbImie;
    private javax.swing.JLabel lbNazwa;
    private javax.swing.JLabel lbNazwisko;
    private javax.swing.JLabel lbNotatki;
    private javax.swing.JRadioButton rbInstytucja;
    private javax.swing.JRadioButton rbOsoba;
    private javax.swing.JTextArea taNotatki;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfImie;
    private javax.swing.JTextField tfNazwa;
    private javax.swing.JTextField tfNazwisko;
    // End of variables declaration//GEN-END:variables
}
