/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import mail.Kontakt;
import mail.listaKontaktow;

/**
 *
 * @author CrossbyLite
 */
public class Kontakty extends javax.swing.JFrame {

    /**
     * Creates new form Kontakty
     */
    
     public void AktualizacjaListy()
    {
        DefaultListModel<String> lm = new DefaultListModel<>();
        String[] zespoly = kontakty.getInfos();       // jakby inicjalizacja listy była poza konstruktorem
        for (String info : zespoly) {
            lm.addElement(info);
        }
        listKontakty.setModel(lm);
    }
     
     protected listaKontaktow kontakty;
     protected static int ile = 0;
     protected JList listaAdresow2;
    
    public Kontakty(MainFrame mf2, JList listaAdresow) {
        initComponents();
        ile++;
        
        listaAdresow2=listaAdresow;
        
        mf = mf2;
        
        this.kontakty = mf2.kontakty;
        
        
        AktualizacjaListy();
        
        
        
        setSize(mf.getSize());
        setLocation(mf.getLocationOnScreen());
        mf.setVisible(false);
        
        btnUsun.setEnabled(false);
        
        //DefaultListModel model = new DefaultListModel();
       // listKontakty = new javax.swing.JList(model);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listKontakty = new javax.swing.JList<>();
        btnDodaj2 = new javax.swing.JButton();
        btnUsun = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButton1.setText("<---");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        listKontakty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listKontaktyMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listKontakty);

        btnDodaj2.setText("Dodaj");
        btnDodaj2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodaj2ActionPerformed(evt);
            }
        });

        btnUsun.setText("Usuń");
        btnUsun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDodaj2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUsun, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(370, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDodaj2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        mf.setVisible(true);
        
        DefaultListModel<String> lm2 = new DefaultListModel<>();
        String[] zespoly = kontakty.getInfos2();       
        for (String info : zespoly) {
            lm2.addElement(info);
        }
        listaAdresow2.setModel(lm2);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnDodaj2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodaj2ActionPerformed
        btnDodaj2.setEnabled(false);
        DodajKontakt dk = new DodajKontakt(listKontakty, btnDodaj2, kontakty);
        dk.setVisible(true);
        dk.setSize(mf.getWidth()/2+50,mf.getHeight()/2+50);
    }//GEN-LAST:event_btnDodaj2ActionPerformed

    private void listKontaktyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listKontaktyMouseClicked
        // TODO add your handling code here:
        btnUsun.setEnabled(true);
    }//GEN-LAST:event_listKontaktyMouseClicked

    private void btnUsunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsunActionPerformed
        // TODO add your handling code here:
        kontakty.usunKontakt(listKontakty.getSelectedIndex());
        int i;
        DefaultListModel model = new DefaultListModel();
    for(i=0; i <= listKontakty.getLastVisibleIndex(); i++)
    {
        if(i != listKontakty.getSelectedIndex())
            model.addElement(listKontakty.getModel().getElementAt(i));
    }
    listKontakty.setModel(model);
    btnUsun.setEnabled(false);
    }//GEN-LAST:event_btnUsunActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       mf.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kontakty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kontakty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kontakty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kontakty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Kontakty().setVisible(true);
            }
        });
    }
    
    private MainFrame mf;
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj2;
    private javax.swing.JButton btnUsun;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listKontakty;
    // End of variables declaration//GEN-END:variables
}
