/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import mail.Kontakt;
import mail.listaKontaktow;
import javax.swing.JList;
import mail.listOdebrane;
import mail.listWyslane;
import mail.Odebrane;
import mail.Wyslane;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JRadioButton;
import mail.Email;



/**
 *
 * @author Michał
 */
public class NowaWiadomosc extends javax.swing.JFrame {

    
    
    protected listWyslane listaWyslanych;    
    protected JList mailwyslane;
    protected JList listamail;
    private JRadioButton isOdebrane;
    
    /**
     * Creates new form Wyswietlenie
     */
    public NowaWiadomosc(MainFrame mf2, listWyslane mailwyslane ,JList listamail, JRadioButton isOdebrane ) {
        initComponents();
        
        this.isOdebrane = isOdebrane;
        mf = mf2;        
        listaWyslanych = mailwyslane;
        lEmaile = listamail;
        
        lError.setVisible(false);
        lErrorEmail.setVisible(false);
        
        
        //MainFrame mf3 = new MainFrame();
        setSize(mf.getSize());
        //setLocation(mf.getLocationOnScreen())
        setLocationRelativeTo(null);              
        
        setResizable(false);
        
        
    }

    private NowaWiadomosc() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPowrot = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taTresc = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lError = new javax.swing.JLabel();
        taDoKogo = new javax.swing.JTextField();
        taTytul = new javax.swing.JTextField();
        lErrorEmail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnPowrot.setText("<---");
        btnPowrot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPowrotActionPerformed(evt);
            }
        });

        taTresc.setColumns(20);
        taTresc.setLineWrap(true);
        taTresc.setRows(5);
        jScrollPane1.setViewportView(taTresc);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Nowa Wiadomość");

        jButton1.setText("Wyślij");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Do kogo:");

        jLabel3.setText("Tytuł: ");

        jLabel4.setText("Treść:");

        lError.setForeground(new java.awt.Color(255, 51, 51));
        lError.setText("Uzupełnij wszystkie wymagane pola!");

        taTytul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taTytulActionPerformed(evt);
            }
        });

        lErrorEmail.setForeground(new java.awt.Color(255, 51, 51));
        lErrorEmail.setText("Niepoprawny email!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPowrot, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(36, 36, 36)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(203, 203, 203)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lError)
                                    .addComponent(jLabel1)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(taDoKogo, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                            .addComponent(taTytul))
                        .addGap(18, 18, 18)
                        .addComponent(lErrorEmail)))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(336, 336, 336))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPowrot, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(15, 15, 15)
                .addComponent(lError)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(taDoKogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lErrorEmail))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(taTytul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4)))
                .addGap(31, 31, 31)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPowrotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPowrotActionPerformed
        // TODO add your handling code here:
        
        dispose();
        mf.button.setEnabled(true);
        //setVisible(false);
        //MainFrame mf = new MainFrame();
        //mf.setVisible(true);
        //pLogowanie.setVisible(false);
    }//GEN-LAST:event_btnPowrotActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        String EMAIL_PATTERN = 
        "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
        + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        
        Pattern pattern = Pattern.compile(EMAIL_PATTERN);
        
        if(taDoKogo.getText().equals("") || taTytul.getText().equals("") )
        {
            lError.setVisible(true);
        }
                           
        else if((pattern.matcher(taDoKogo.getText()).matches() == false))
        {
            lErrorEmail.setVisible(true);
        }
        
        
        else
        {
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm");
            Date date = new Date();
            String przerwa = "                              ";
            listaWyslanych.dodajWyslane(new Wyslane(taDoKogo.getText()+przerwa,taTytul.getText()+przerwa,dateFormat.format(date)+przerwa,taTresc.getText()));
            if(!isOdebrane.isSelected())
            {
                DefaultListModel<String> lm = new DefaultListModel<>();
                String[] emaile = listaWyslanych.getInfos();       // jakby inicjalizacja listy była poza konstruktorem
                for (String info : emaile) {
                    lm.addElement(info);
                }      
                lEmaile.setModel(lm);
            }
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void taTytulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taTytulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taTytulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NowaWiadomosc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NowaWiadomosc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NowaWiadomosc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NowaWiadomosc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NowaWiadomosc().setVisible(true);
            }
        });
    }
    
    private MainFrame mf;
    //private listOdebrane listaOdebranych;
    //private listWyslane listaWyslanych;
    private JList lEmaile;       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPowrot;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lError;
    private javax.swing.JLabel lErrorEmail;
    private javax.swing.JTextField taDoKogo;
    private javax.swing.JTextArea taTresc;
    private javax.swing.JTextField taTytul;
    // End of variables declaration//GEN-END:variables
}
