/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.Scanner;
import javax.swing.DefaultListModel;
import mail.Kontakt;
import mail.listaKontaktow;
import javax.swing.JList;
import mail.listOdebrane;
import mail.listWyslane;
import mail.Odebrane;
import mail.Wyslane;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import mail.Email;



/**
 *
 * @author Michał
 */
public class Wyswietlenie extends javax.swing.JFrame {

    
    protected listOdebrane listaOdebranych;
    protected listWyslane listaWyslanych;
    protected JList mailodebrane;
    protected JList mailwyslane;
    protected JList listamail;
    
    /**
     * Creates new form Wyswietlenie
     */
    public Wyswietlenie(MainFrame mf2, listOdebrane mailodebrane , listWyslane mailwyslane ,JList listamail ) {
        initComponents();
        
        mf = mf2;
        listaOdebranych = mailodebrane;
        listaWyslanych = mailwyslane;
        lEmaile = listamail;
        
        
        //MainFrame mf3 = new MainFrame();
        setSize(mf.getSize());
        //setLocation(mf.getLocationOnScreen())
        setLocationRelativeTo(null);
        
        int index = lEmaile.getSelectedIndex();
        taTytul.setText("");
        taTytul.setText(lEmaile.getSelectedValue().toString());
        
        lzalacznik.setVisible(false);
        
        if(mf.isOdebrane.isSelected())
        {
            taTresc.setText(listaOdebranych.getTresci()[index]);
            
            if(listaOdebranych.czyZalacznik(index))
                lzalacznik.setVisible(true);
        }
        
        else 
        {
            taTresc.setText(listaWyslanych.getTresci()[index]);
            if(listaWyslanych.czyZalacznik(index))
                lzalacznik.setVisible(true);
        }
        
        setResizable(false);
        
        
    }

    private Wyswietlenie() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPowrot = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taTresc = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        taTytul = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        lzalacznik = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnPowrot.setText("<---");
        btnPowrot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPowrotActionPerformed(evt);
            }
        });

        taTresc.setColumns(20);
        taTresc.setLineWrap(true);
        taTresc.setRows(5);
        jScrollPane1.setViewportView(taTresc);

        taTytul.setColumns(20);
        taTytul.setRows(5);
        jScrollPane2.setViewportView(taTytul);

        jButton1.setText("Zapisz do pliku");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lzalacznik.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lzalacznik.setText("załącznik");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPowrot, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lzalacznik, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPowrot, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(lzalacznik))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPowrotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPowrotActionPerformed
        // TODO add your handling code here:
        
        dispose();
        mf.button.setEnabled(true);
        //setVisible(false);
        //MainFrame mf = new MainFrame();
        //mf.setVisible(true);
        //pLogowanie.setVisible(false);
    }//GEN-LAST:event_btnPowrotActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        JFileChooser fc = new JFileChooser();
        if (fc.showSaveDialog(null) == JFileChooser.APPROVE_OPTION)
        {
            File pliczek = fc.getSelectedFile();
            
            try
            {
                PrintWriter pw = new PrintWriter(pliczek);
                Scanner odczyt = new Scanner(taTresc.getText());
                while(odczyt.hasNext())
                {
                    pw.println(odczyt.nextLine() + "\n");
                }
                
                pw.close();
                
            }
            catch(FileNotFoundException e1)
            {
                e1.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Wyswietlenie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Wyswietlenie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Wyswietlenie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Wyswietlenie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Wyswietlenie().setVisible(true);
            }
        });
    }
    
    private MainFrame mf;
    //private listOdebrane listaOdebranych;
    //private listWyslane listaWyslanych;
    private JList lEmaile;       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPowrot;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lzalacznik;
    private javax.swing.JTextArea taTresc;
    private javax.swing.JTextArea taTytul;
    // End of variables declaration//GEN-END:variables
}
